/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzaVypisovRouteImport } from './routes/analyza-vypisov'
import { Route as OsobyRouteImport } from './routes/osoby'
import { Route as ViacRouteImport } from './routes/viac'
import { Route as VztahyRouteImport } from './routes/vztahy'
import { Route as ZbraneRouteImport } from './routes/zbrane'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzaVypisovRoute = AnalyzaVypisovRouteImport.update({
  id: '/analyza-vypisov',
  path: '/analyza-vypisov',
  getParentRoute: () => rootRouteImport,
} as any)
const OsobyRoute = OsobyRouteImport.update({
  id: '/osoby',
  path: '/osoby',
  getParentRoute: () => rootRouteImport,
} as any)
const ViacRoute = ViacRouteImport.update({
  id: '/viac',
  path: '/viac',
  getParentRoute: () => rootRouteImport,
} as any)
const VztahyRoute = VztahyRouteImport.update({
  id: '/vztahy',
  path: '/vztahy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZbraneRoute = ZbraneRouteImport.update({
  id: '/zbrane',
  path: '/zbrane',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyza-vypisov': typeof AnalyzaVypisovRoute
  '/osoby': typeof OsobyRoute
  '/viac': typeof ViacRoute
  '/vztahy': typeof VztahyRoute
  '/zbrane': typeof ZbraneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyza-vypisov': typeof AnalyzaVypisovRoute
  '/osoby': typeof OsobyRoute
  '/viac': typeof ViacRoute
  '/vztahy': typeof VztahyRoute
  '/zbrane': typeof ZbraneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyza-vypisov': typeof AnalyzaVypisovRoute
  '/osoby': typeof OsobyRoute
  '/viac': typeof ViacRoute
  '/vztahy': typeof VztahyRoute
  '/zbrane': typeof ZbraneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analyza-vypisov' | '/osoby' | '/viac' | '/vztahy' | '/zbrane'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyza-vypisov' | '/osoby' | '/viac' | '/vztahy' | '/zbrane'
  id:
    | '__root__'
    | '/'
    | '/analyza-vypisov'
    | '/osoby'
    | '/viac'
    | '/vztahy'
    | '/zbrane'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzaVypisovRoute: typeof AnalyzaVypisovRoute
  OsobyRoute: typeof OsobyRoute
  ViacRoute: typeof ViacRoute
  VztahyRoute: typeof VztahyRoute
  ZbraneRoute: typeof ZbraneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyza-vypisov': {
      id: '/analyza-vypisov'
      path: '/analyza-vypisov'
      fullPath: '/analyza-vypisov'
      preLoaderRoute: typeof AnalyzaVypisovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osoby': {
      id: '/osoby'
      path: '/osoby'
      fullPath: '/osoby'
      preLoaderRoute: typeof OsobyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viac': {
      id: '/viac'
      path: '/viac'
      fullPath: '/viac'
      preLoaderRoute: typeof ViacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vztahy': {
      id: '/vztahy'
      path: '/vztahy'
      fullPath: '/vztahy'
      preLoaderRoute: typeof VztahyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zbrane': {
      id: '/zbrane'
      path: '/zbrane'
      fullPath: '/zbrane'
      preLoaderRoute: typeof ZbraneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzaVypisovRoute: AnalyzaVypisovRoute,
  OsobyRoute: OsobyRoute,
  ViacRoute: ViacRoute,
  VztahyRoute: VztahyRoute,
  ZbraneRoute: ZbraneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
